import { type ReactNode } from "react";
import {
  Wifi,
  Wind,
  Flame,
  UtensilsCrossed,
  Car,
  Mountain,
  Waves,
  Umbrella,
  ChefHat,
  Tv,
  Dumbbell,
  Sprout,
  Puzzle,
  Bath,
  View,
  Sparkles,
  Coffee,
  ConciergeBell,
  Anchor,
  Sailboat,
} from "lucide-react";

export const amenityIcons: Record<string, ReactNode> = {
  WiFi: <Wifi size={20} />,
  "Aire acondicionado": <Wind size={20} />,
  Chimenea: <Flame size={20} />,
  "Cocina equipada": <UtensilsCrossed size={20} />,
  Cocina: <UtensilsCrossed size={20} />,
  "Cocina gourmet": <UtensilsCrossed size={20} />,
  Estacionamiento: <Car size={20} />,
  "Vista a la montaña": <Mountain size={20} />,
  "Piscina privada": <Waves size={20} />,
  Piscina: <Waves size={20} />,
  "Piscina del edificio": <Waves size={20} />,
  BBQ: <Flame size={20} />,
  "Playa privada": <Umbrella size={20} />,
  "Chef disponible": <ChefHat size={20} />,
  TV: <Tv size={20} />,
  "Gimnasio del edificio": <Dumbbell size={20} />,
  Gimnasio: <Dumbbell size={20} />,
  Jardín: <Sprout size={20} />,
  "Zona de juegos": <Puzzle size={20} />,
  Jacuzzi: <Bath size={20} />,
  Terraza: <View size={20} />,
  Balcón: <View size={20} />,
  "Servicio de limpieza": <Sparkles size={20} />,
  "Desayuno incluido": <Coffee size={20} />,
  "Room service": <ConciergeBell size={20} />,
  Spa: <Sparkles size={20} />,
  "Muelle privado": <Anchor size={20} />,
  Kayaks: <Sailboat size={20} />,
  Fogata: <Flame size={20} />,
};
